# .github/workflows/development.yml
name: Development pipeline

on:
  push:

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests

      - name: Run Flake8
        run: |
          source .venv/bin/activate
          flake8 leaffliction  --disable-noqa
          

      - name: Build project
        run: |
          source .venv/bin/activate
          make data
          mkdir data/processed
          mkdir data/model
          mkdir artifact_save
          python leaffliction/tools/improve_dataset.py data/external/images data/processed/augmented/
          python leaffliction/train.py data/processed/augmented --epoch 20 --plot --save_mode --batch_ratio 0.8 --save_dir data/model
          zip -r artifact_save/data.zip data

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: artifact_save/
