# .github/workflows/development.yml
name: Development pipeline

on:
  push:

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  test:
    runs-on: ubuntu-latest
    needs: create-virtualenv

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv


      - name: Run tests
        run: |
          pytest tests

      - name: Run Flake8
        run: |
          flake8 leaffliction --disable-noqa --config setup.cfg

  data:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Import_data
        run: |
          make data

      - name: Improve_dataset
        run: |
          mkdir -p data/processed
          python leaffliction/tools/improve_dataset.py data/external/images data/processed/augmented/

      - name: Zip_data
        run: |
          mkdir -p data_artifact
          zip -r data_artifact/data.zip data

      - name: Upload data directory
        uses: actions/upload-artifact@v4
        with:
          name: data-artifact
          path: data_artifact

  train:
    runs-on: ubuntu-latest
    needs: [data]
    if: contains(github.event.head_commit.message, '--train_model')

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Download data artifact
        uses: actions/download-artifact@v4
        with:
          name: data-artifact
          path: data_artifact

      - name: Unzip data artifact
        run: |
          unzip data_artifact/data.zip -d data

      - name: Train_model
        run: |
          mkdir -p data/model
          python leaffliction/train.py data/processed/augmented --epoch 20 --plot --save_mode --batch_ratio 0.8 --save_dir data/model

      - name: Zip_data
        run: |
          mkdir -p train_artifact
          zip -r train_artifact/train.zip data

      - name: Upload data directory
        uses: actions/upload-artifact@v4
        with:
          name: train-artifact
          path: train_artifact
